project_id = "iwrrijemxtudyakmhajk"

[functions.webhook-kiwify]
verify_jwt = false

[functions.webhook-hotmart]
verify_jwt = false

[functions.import-csv]
verify_jwt = false

[functions.sync-meta]
verify_jwt = false

[functions.sync-google]
verify_jwt = false

[functions.list-meta-campaigns]
verify_jwt = false

[functions.sync-whatsapp]
verify_jwt = false

[functions.sync-kiwify]
verify_jwt = false

[functions.sync-hotmart]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.auto-sync]
verify_jwt = false

[functions.tracking-pixel]
verify_jwt = false

[functions.send-whatsapp-report]
verify_jwt = false

[functions.ai-forecast]
verify_jwt = false

[functions.sync-agsell]
verify_jwt = false

[functions.webhook-agsell]
verify_jwt = false
