// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsqckbceejdshbmjingp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzcWNrYmNlZWpkc2hibWppbmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNjMxNTIsImV4cCI6MjA5MTgzOTE1Mn0.oJMSqajONdCF_rcTNJVOyPU-yNmbuDZItP7EogSLbiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});